### PR TITLE
feat: Added accessibility (allow tab focus and enabled keyboard events)

### PR DESCRIPTION
**Pull request by MazGrasl**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

### CODE REVIEW

**Comment by MazGrasl** [comment]
@trickeyone On my local machine "yarn ci" executes successfully, and I've committed and pushed the changes proposed by clang, yet the Travis CI build fails with a message to run clang on misc/generate-stackblitz.ts (which I've never touched in the first place).
Any ideas how I can get the build to run?

**Comment by trickeyone** [comment]
@MazGrasl Weird. Sorry, I've been dealing with other duties at work and haven't been able to followup. I'll try to look at it tomorrow night. This is a good addition, thanks for the work on it!

**Comment by trickeyone** [comment]
@MazGrasl Ok, sorry, more work stuff. Actually, if you look at the changed files of your PR, you'll see that you did change the `misc/generate-stackblitz.ts` file. If you run the command it's telling you and push that, it'll fix the issue.

**Comment by MazGrasl** [comment]
@trickeyone I thought that's what I did. I'll try it again tomorrow and get back to you.

**Comment by MazGrasl** [comment]
@trickeyone I'm even more confused. After reverting the clang changes the travis build works now, but if I try to run "yarn ci" on my machine I get the same error that travis had earlier.
I'll leave it as is now (since I don't need to run CI on my machine) but it's very weird.
Maybe the behaviour is dependant on yarn/npm/node/gulp version? I checked and clang uses NPM version 1.4.0, which is similar to what travis uses.
I have yarn 1.22.4, npm 6.12.0, node v10.15.3, gulp 4.0.2.
Maybe this will help you if you encounter a similar problem in the future (or if you really want to dig into this issue).

Anyway, would be great if you can merge the PR soon.
Thanks for your help!

**Comment by trickeyone** [comment]
@MazGrasl  I'll try to get a release out tonight

**Comment by trickeyone** [comment]
ok, @MazGrasl new release created and published to npmjs.com
Thanks for the contribution!

**Pull request merged**
